paths:
  - Configuration/TypoScript/

sniffs:
  - class: Helmich\TypoScriptLint\Linter\Sniff\IndentationSniff
    parameters:
      indentPerLevel: 4
      useSpaces: true
  - class: Helmich\TypoScriptLint\Linter\Sniff\DeadCodeSniff
  - class: Helmich\TypoScriptLint\Linter\Sniff\OperatorWhitespaceSniff
  - class: Helmich\TypoScriptLint\Linter\Sniff\DuplicateAssignmentSniff
  - class: Helmich\TypoScriptLint\Linter\Sniff\EmptyBlockSniff
  - class: Helmich\TypoScriptLint\Linter\Sniff\NestingConsistencySniff

filePatterns:
  - "*.typoscript"
  - "*.ts"
  - "*.txt"