services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  queryBuilder.token:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_apitoken_domain_model_token'

  CPSIT\ApiToken\:
    resource: '../Classes/*'

  CPSIT\ApiToken\Middleware\ApiKeyAuthenticator:
    public: true

  CPSIT\Controller\Backend\TokenController:
    public: true

  CPSIT\ApiToken\Service\TokenBuildService:
    public: true

  CPSIT\ApiToken\Domain\Repository\TokenRepository:
    autowire: false
    public: true
    arguments:
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\PersistenceManagerInterface'
      $queryBuilder: '@queryBuilder.token'
  CPSIT\ApiToken\Command\GenerateTokenCommand:
    tags:
      - name: 'console.command'
        command: 'apitoken:generate'
        description: 'Generate api token for authentication.'
        # not required, defaults to false
        hidden: false

